# Generated by Django 3.0.8 on 2020-07-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='blogimg')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
