# Generated by Django 3.0.5 on 2020-07-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200724_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Blog',
        ),
    ]
